### ISSUE TITLE
Stop mixing camelCase and snake_case in code!

### ISSUE THREAD

**Issue by mmniazi** [AliFlux/MapTilesDownloader#1]
nice work btw 😉

**Comment by AliFlux** [comment]
Ah yes. The two functions I copied from stackoverflow. Forgot to change their cases :P Send a pull request

**Comment by AliFlux** [comment]
That code was unused anyway. In the latest commit (c0a0d10), it's removed.

**Comment by mmniazi** [comment]
👍
