### ISSUE TITLE
App eventually crashes

### ISSUE THREAD

**Issue by Exscotticus** [AliFlux/MapTilesDownloader#3]
Love this app! However, when dealing with tens of thousands of tiles in a single go, the browser UI eventually crashes (Chrome says, "Aw, Snap! Something went wrong while displaying this webpage."). I'd say 50k tiles seems to be the limit.

I thought maybe it's a memory leak related to the ever-expanding **log-view** container. But I commented out the **logItemRaw()** function and it still happens. It's worth noting that the logging definitely slows down the app over time. It would be better to implement a fixed sized queue that only shows the last 25 log events.

**Comment by AliFlux** [comment]
Hi

You can try downloading maps in different rectangle segments. The code is resume-supported and ignores tiles if they are already there.

But for an actual fix, can you try profiling via your browser to see what exactly is slowing it down?

**Comment by fjifdg895ngdf** [comment]
The slow down is not as much of an issue as the app eventually crashing. I think they're related; I think it's running out of memory.

Are you able to download 100k tiles in one go? I can't. Crashes.

Let's say I'm using Chrome. What exactly would you like me to test?

**Comment by AliFlux** [comment]
Can you elaborate on what is crashing? I assume that the chrome UI crashes. In that case, can you use system monitor or task manager to show the memory/CPU graph while downloading?

**Comment by fjifdg895ngdf** [comment]
The culprit is "Google Chrome Helper (Renderer)".

I watched it double in memory usage and eventually consume 102.66% of CPU before it crashed.

**Comment by AliFlux** [comment]
I'll have to check into that. I just downloaded about 10k tiles and it worked fine, will try a bigger subset

**Comment by fjifdg895ngdf** [comment]
As I mentioned, you need to try more than 50k for the issue to manifest.

I'm trying a different browser.

**Comment by fjifdg895ngdf** [comment]
I tried Firefox and exceeded 200k files. As far as I'm concerned, this isn't a coding issue; it's web browser issue. I'm closing the issue.

**Comment by lade043** [comment]
I stumbled upon the same issue when downloading large amounts (+250k) of tiles. I use Firefox 79.0 on Ubuntu. Firefox is using with just this tab open in the end 15 of 16 GB of memory in my system and thus crashing the entire system.
I also use a modded version of log-view, but it still crashes at around 250 000 downloaded tiles.

I'm now doing it in multiple segments but a fix would be nice.

**Comment by Fabioni** [comment]
Any update on this?

**Comment by Fabioni** [comment]
The problem seems to be the https://github.com/AliFlux/MapTilesDownloader/blob/9c2d9ac5fe6455ba8ca2903a96d05ce80fe254e3/src/UI/main.js#L552
